# Generated by Django 3.2.3 on 2021-05-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_endereco_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='updated_at',
        ),
    ]
