# Generated by Django 3.2.3 on 2021-06-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_alter_servico_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='nrTelCelular',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='nrTelFixo',
        ),
        migrations.AddField(
            model_name='servico',
            name='telefone01',
            field=models.CharField(default=1, max_length=11, verbose_name='Telefone 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='telefone02',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone 2(Opcional)'),
        ),
    ]
