# Generated by Django 3.2.3 on 2021-06-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_auto_20210621_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='telefone02',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone 2 (Opcional)'),
        ),
    ]
