# Generated by Django 3.2.3 on 2021-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_alter_servico_telefone02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
