# Generated by Django 3.2.3 on 2021-07-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_alter_endereco_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ativo',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
